global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web-hook' # Standaard ontvanger

receivers:
  - name: 'web-hook'
    # Hier kun je later E-mail, Slack, Discord, PagerDuty etc toevoegen.
    # Voor nu logging we het alleen in de container logs of sturen we niks.
    webhook_configs:
      - url: 'http://127.0.0.1:5001/' # Dummy URL
